### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by eteeselink** [hijonathan/moment.twitter#12]
Just so you know, because you're not publishing a license, I break the law in most countries by using your code. 

Thanks anyway :-)

**Comment by hijonathan** [comment]
Thanks for reporting. Should be all set now. I used the same license as found in [moment core](https://github.com/moment/moment/blob/develop/LICENSE).

**Comment by eteeselink** [comment]
Great, thanks!

**Comment by dantman** [comment]
package.json, component.json, and bower.json still incorrectly state `"license": "BSD-2-Clause",`. instead of `MIT`.
